[package]
name = "poker"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
indextree = "*"
log = "*"

[dev-dependencies]
env_logger = "*"
